//
// Created by madina on 19/12/17.
//

#pragma once

typedef enum USER_TYPE USER_TYPE;
typedef enum MESSAGE_TYPE MESSAGE_TYPE;
typedef enum STATE STATE;

enum USER_TYPE{
    CLIENT, DRIVER, SERVER, SYSADMIN
};

enum MESSAGE_TYPE{
    AUTHENTIFICATION = 0, LOG_IN = 1, AUTH_SUCCESSFUL = 2, ACCESS_DENIED = 3,
    ORDER_REQUEST = 4, ORDER_GET = 5, ORDER_CANCEL = 6, CLIENT_CANCEL_ORDER = 7, ORDER_ACCEPTED = 8,
    STATE_CHANGE = 9, LOCATION_CHANGE = 10, DRIVER_ARRIVED = 11
};

enum STATE{
    FREE, DRIVE_TO_SOURCE, WAITING_CLIENT, PICKED_UP, DRIVER_OFFLINE
};