//
// Created by madina on 19/12/17.
//

#pragma once

typedef enum USER_TYPE USER_TYPE;
typedef enum MESSAGE_TYPE MESSAGE_TYPE;
typedef enum STATE STATE;

enum USER_TYPE{
    CLIENT, DRIVER, SERVER, SYSADMIN
};

enum MESSAGE_TYPE{
    AUTHENTIFICATION,
    LOG_IN,
    ORDER_GET,
    ORDER_CANCEL,
    STATE_CHANGE,
    LOCATION_CHANGE,
    ACCESS_DENIED,
    ACCESS_SUCCESSFUL
};

enum STATE{
    FREE, DRIVE_TO_SOURCE, WAITING_CLIENT, PICKED_UP
};